; Configuration file for Fly-E3-Pro-v3 (firmware version 3.5)
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.5.0-STM32+1 on Sun Feb 02 2025 20:10:53 GMT-0600 (Central Standard Time)

; General preferences
G90                                                  ; send absolute coordinates...
M83                                                  ; ...but relative extruder moves
M550 P"Stinger"                                      ; set printer name

; Network
M552 S1                                              ; enable network
M586 P0 S1                                           ; enable HTTP
M586 P1 S0                                           ; disable FTP
M586 P2 S0                                           ; disable Telnet

; define the relay pin and turn it on deliberately, later M81/M80 will work to power cycle drivers
M80 C"PSON"

; Drives
M84 S30                                              ; Set idle timeout

; Configure printer as 4-axis variant:
M98 P"to4axis.g" 

; Accelerometer -- OPTIONAL
; M955 P0 C"PB_2+PA_10" I46

; Input shaping
; M593 P"zvddd" F38

; Temperature sensors:
M308 S2 P"boardtemp" Y"thermistor" A"Fly Board Temp" T100000 B4092 
M308 S0 P"e0temp" Y"thermistor" A"Extruder" T100000 B4956 C1.587780e-7 ; configure sensor 0 as thermistor on pin e0temp
M308 S1 P"bedtemp" Y"thermistor" T100000 A"Bed"

; Heaters
M950 H0 C"e0heat" T0                                       ; create nozzle heater output on e0heat and map it to sensor 0
M307 H0 R2.703 K0.364:0.000 D11.05 E1.35 S1.00 B0 V23.7    ; pwm config from autotune
M143 H0 S270                                               ; set temperature limit for heater 0
M302 P0                                                    ; disallow cold extrudes

; Bed
M950 H1 C"bed" T1                                          ; create nozzle heater output on e0heat and map it to sensor 0
; M307 H1 R2.703 K0.364:0.000 D11.05 E1.35 S1.00 B0 V23.7    ; pwm config from autotune
M143 H1 S90                                                ; set temperature limit for bed

; Fans
M950 F0 C"fan1"                                            ; create fan 0 on pin fan0 and set its frequency
M106 P0 S0 H0 T50                                          ; set fan 0 value. Thermostatic control is turned on

M950 F1 C"!PA_7" Q50                                       ; create fan 1 on pin PA_0

; Tools
M563 P0 D0 F0 H0                                           ; define tool 0
G10 P0 X0 Y0 Z0                                            ; set tool 0 axis offsets
G10 P0 R0 S0                                               ; set initial tool 0 active and standby temperatures to 0C
T0                                                         ; select tool
