; runonce.g
; called after config.g. When it has been executed, it is automatically deleted!
;
; generated by RepRapFirmware Configuration Tool v3.5.0-STM32+1 on Sun Feb 02 2025 20:10:53 GMT-0600 (Central Standard Time)
M552 S0                            ; disable network
G4 S5                              ; wait half a second
M587 S"petoria" P"13311331ff" ; configure WiFi
G4 S5
M552 S1                            ; enable network
