; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.0-STM32+1 on Sun Feb 02 2025 20:10:55 GMT-0600 (Central Standard Time)
; Wait for set temperatures to be reached
M116 P0

